server:
  port: 80
spring:
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp13n346h0e86y28vxo.mysql.rds.aliyuncs.com:3306/login?characterEncoding=utf-8&useSSL=false
    username: aliyun_mysql
    password: 13616962575swh@
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #控制台打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志打印sql
logging:
  level:
    com.eth.wallet.mapper: debug
  file:
   path: /var/log/tomcat


#配置阿里云oss数据库
#阿里云地域节点
endpoint: http://oss-cn-beijing.aliyuncs.com
#bucket名称
bucketName: suwenhai
#RAM id 与秘钥
accessKeyId: LTAI4FzS2TFSg7RxL1gWm9TP
accessKeySecret: uAuy57MMfnOAV8EXeRTxfvL4HzP27T
