server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp13n346h0e86y28vxo.mysql.rds.aliyuncs.com:3306/login?characterEncoding=utf-8&useSSL=false
    username: aliyun_mysql
    password: 13616962575swh@
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml

